plugins:
  - jekyll-paginate
  - jekyll-redirect-from

title: 梅花雀莊
description: 何震邦的個人網站，通常寫電腦和橋牌相關的文章，未來可能會寫關於日本麻將的東西
paginate: 10
paginate_path: /page/:num/
permalink: /:title/
timezone: Asia/Taipei

defaults:
  - scope:
        path: ""
    values:
        author: jdh8
